DROP DATABASE IF EXISTS BR_CORTES;

CREATE DATABASE IF NOT EXISTS BD_CORTES;

USE BD_CORTES;

CREATE TABLE TB_PERFIL(
  ID_PERFIL INT,
  DS_PERFIL VARCHAR(30),
  PRIMARY KEY (ID_PERFIL)
);

CREATE TABLE TB_USUARIO(
  ID_USUARIO INT,
  DS_LOGIN   VARCHAR(30),
  DS_SENHA   VARCHAR(15),
  ID_PERFIL  INT,
  PRIMARY KEY (ID_USUARIO),
  FOREIGN KEY (ID_PERFIL) REFERENCES TB_PERFIL (ID_PERFIL)
);

CREATE TABLE TB_CORTE(
  ID_CORTE    INT,
  DS_CORTE    VARCHAR(50),
  DS_ABREV    VARCHAR(30),
  VL_PRECO_KG NUMERIC(5,2),
  PRIMARY KEY (ID_CORTE)
);


CREATE TABLE TB_SUGESTAO(
  ID_SUGESTAO INT,
  DS_SUGESTAO VARCHAR(50),
  DS_ABREV    VARCHAR(30),
  PRIMARY KEY (ID_SUGESTAO)
);

CREATE TABLE TB_CORTE_SUGESTAO(
  ID_CORTE INT,
  ID_SUGESTAO INT,
  PRIMARY KEY (ID_CORTE, ID_SUGESTAO),
  FOREIGN KEY (ID_CORTE) REFERENCES TB_CORTE (ID_CORTE),
  FOREIGN KEY (ID_SUGESTAO) REFERENCES TB_SUGESTAO (ID_SUGESTAO)
);